### ISSUE TITLE
Quizz support

### ISSUE THREAD

**Issue by Th0rgal** [starknet-id/quest_server#56]
The goal is to add support for a new kind of task built in the website: Quiz.
Here is a figma of the frontend part: https://www.figma.com/file/fh0OAvj4AS08kHoSxu3DkE/Starknet-Quest?type=design&node-id=1099%3A515&mode=design&t=kBC2zLniTgX5fcur-1

The user will have to answer a list of questions. They will know the result at the end of the quiz. There are 3 kinds of questions possible:
- n out of m choices of text options
- n out of m choices of image options
- ordering text options

Each question comes with a specific layout. We will start with two layouts:
- default (only showing the options)
- illustrated_left (showing an image at the left and the options at the right)

The server should be able to load the quizzes from a new config section:
```toml
[quizzes]

[quizzes.uniswap_oracle]
name = "Uniswap Oracle"
desc = "Become a true Uniswap Oracle, answer clever questions, and unlock valuable DeFi knowledge."
intro = "Welcome to the Uniswap Unraveled quiz – an exhilarating journey into the heart of decentralized finance (DeFi). Test your knowledge, dive into Uniswap's ecosystem, and unlock the secrets of DeFi. Get ready to become a DeFi expert as you answer questions and earn rewards. Are you up for the challenge? Let's get started!"

[[quizzes.uniswap_oracle.questions]]
kind = "text_choice"
layout = "default"
question = "How is liquidity provided in Uniswap?"
options = ["Through centralized exchanges", "By liquidity providers depositing funds into smart contracts", "By Uniswap's governance voting on liquidity allocation", "Through a Proof-of-Stake mechanism"]
correct_answer = 2

[[quizzes.uniswap_oracle.questions]]
kind = "image_choice"
layout = "default"
question = "Which token represents the logo of Uniswap?"
options = [ "/uniswap_oracle/bear.webp", "/uniswap_oracle/deer.webp", "/uniswap_oracle/tigger.webp", "/uniswap_oracle/unicorn.webp" ]
correct_answer = 4

[[quizzes.uniswap_oracle.questions]]
kind = "text_choice"
layout = "illustrated_left"
question = "Does this token represent the logo of Uniswap?"
options = ["True", "False"]
correct_answer = 1
image_for_layout = "/uniswap_oracle/unicorn.webp"

[[quizzes.uniswap_oracle.questions]]
kind = "ordering"
layout = "default"
question = "Arrange the following steps in the correct order to perform a swap on Uniswap:"
options = [ "Choose the token you want to swap", "Confirm the transaction", "Connect your wallet to Uniswap", "Select the desired amount for the swap", "Receive the swapped tokens in your wallet", "Review the transaction details and gas fees"]
correct_order = [3, 1, 4, 6, 2, 5]

```

We need:
- endpoint for loading quizz description
- method for verifying a quizz answer
